import './globals.css';
import { Inter, Outfit } from 'next/font/google';
import AppProvider from './provider';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Nrityashala',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
